// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhszakxbswspznmuozqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoc3pha3hic3dzcHpubXVvenFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzI1OTIsImV4cCI6MjA3Mzk0ODU5Mn0.J9cOwesZXC0fidlPj62-kYABJGPoO6LAzYiU3lq88DQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});